services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "127.0.0.1:8010:8000"
    volumes:
      - ./backend/data:/app/backend/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_BASE_URL=http://madrid-de-arbol-en-arbol.datanalytics.com
    ports:
      - "127.0.0.1:8011:80"
    depends_on:
      - backend
    restart: always